version: "3"

services:
  app:
    build: .
    container_name: codeflix-catalog-app
    entrypoint: ./.docker/entrypoint.sh
    environment:
      - HOST=0.0.0.0
      - PORT=3333
    ports:
      - "3333:3333"
    volumes:
      - .:/home/node/app
    networks:
      - app-network
      - codeflix-microservice-rabbitmq_catalog-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.7.1
    container_name: codeflix-catalog-elasticsearch
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms128m -Xmx128m"
    ports:
      - "9200:9200"
    volumes:
      - ./.docker/elasticdata:/usr/share/elasticsearch/data
    networks:
      - app-network

  kibana:
    image: docker.elastic.co/kibana/kibana:7.7.1
    container_name: codeflix-catalog-kibana
    ports:
      - "5601:5601"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
  codeflix-microservice-rabbitmq_catalog-network:
    external: true
