version: "3"

services:
  app:
    build: .
    container_name: codeflix-catalog-app
    entrypoint: ./.docker/entrypoint.sh
    environment:
      - HOST=0.0.0.0
      - PORT=3333
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
